### ISSUE TITLE
Security - todo

### ISSUE THREAD

**Issue by zerai** [zerai/oberdan8#17]
Production config:

- [ ] set encoder argon2i (libreria sodium disponibile)
- [x] Login page layout - https://getbootstrap.com/docs/4.6/examples/sign-in/
- [x] Cli create 1 admin
